import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — Tipora',
  description: 'Terms of service for using the Tipora platform.',
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl py-8">
      <h1 className="text-3xl font-bold text-white">Terms of Service</h1>
      <p className="mt-2 text-sm text-zinc-500">Last updated: April 2026</p>

      <div className="mt-8 space-y-6 text-zinc-400 leading-relaxed">
        <h2 className="text-xl font-semibold text-white">1. Service Description</h2>
        <p>
          Tipora (&ldquo;the Service&rdquo;) is a football tipping and analytics platform operated at
          tipora.bet. We provide data-driven tips, accumulator suggestions and profit/loss tracking.
          We do not place bets, accept deposits or handle any user funds.
        </p>

        <h2 className="text-xl font-semibold text-white">2. Eligibility</h2>
        <p>
          You must be at least 18 years old (or the legal gambling age in your jurisdiction) to use
          this Service. By using Tipora, you confirm that you meet this requirement.
        </p>

        <h2 className="text-xl font-semibold text-white">3. No Guarantee of Profit</h2>
        <p>
          Tips are generated by algorithmic analysis and do not guarantee profit. Past performance
          does not indicate future results. You are solely responsible for any betting decisions
          you make based on our content.
        </p>

        <h2 className="text-xl font-semibold text-white">4. Subscriptions</h2>
        <p>
          Pro subscriptions are billed monthly via Stripe. You may cancel at any time. Refunds are
          not provided for partial billing periods. Free tier access may be modified at our discretion.
        </p>

        <h2 className="text-xl font-semibold text-white">5. Intellectual Property</h2>
        <p>
          All content, data analysis, confidence scores and tip selections are the intellectual
          property of Tipora. You may not reproduce, redistribute or resell our content without
          written permission.
        </p>

        <h2 className="text-xl font-semibold text-white">6. Limitation of Liability</h2>
        <p>
          Tipora is provided &ldquo;as is&rdquo; without warranty. We are not liable for any losses
          incurred from betting based on our tips. Our maximum liability is limited to the
          subscription fees you have paid in the preceding 12 months.
        </p>

        <h2 className="text-xl font-semibold text-white">7. Changes to Terms</h2>
        <p>
          We may update these terms at any time. Continued use of the Service after changes
          constitutes acceptance. Material changes will be communicated via email to registered users.
        </p>
      </div>
    </div>
  );
}
